In [2]:
import numpy as np

A = np.array([[56.0,0.0,4.4,68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]])

print(A)
#A is a 3,4 matrix

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [13]:
#axis = sum vertically along the column
#1 is row sum
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [11]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [20]:
#always create matrixes like this :
a = np.random.randn(5,1)
print(a)


[[-1.11298494]
 [-1.4773948 ]
 [-0.55154007]
 [ 1.56739651]
 [-0.56391078]]


In [21]:
print(a.shape)
#don't use this

(5, 1)


In [22]:
print(a.T)

[[-1.11298494 -1.4773948  -0.55154007  1.56739651 -0.56391078]]


In [23]:
print(np.dot(a,a.T))

[[ 1.23873547  1.64431816  0.61385579 -1.7444887   0.62762421]
 [ 1.64431816  2.18269539  0.81484243 -2.31566345  0.83311886]
 [ 0.61385579  0.81484243  0.30419645 -0.86448197  0.31101939]
 [-1.7444887  -2.31566345 -0.86448197  2.45673181 -0.88387179]
 [ 0.62762421  0.83311886  0.31101939 -0.88387179  0.31799537]]


In [24]:
a = np.random.randn(32,32,3)
print(a)

[[[ 0.17193314  0.28921531 -0.34965604]
  [ 0.27612768  1.09868034  0.50501792]
  [ 0.21364033  1.54554704  0.82927876]
  ...
  [ 0.3414704   0.43046542  1.23406383]
  [ 1.8785204  -0.20562577  0.81275012]
  [ 1.72034824 -0.13281183 -0.26687136]]

 [[ 0.8985661  -0.02968264  0.4716569 ]
  [ 0.59702671  0.72721656  0.48337736]
  [-0.32762297 -0.43202496 -0.70324332]
  ...
  [-0.18919069 -0.22063337  0.07145886]
  [ 0.22110259  0.09568905  1.47704708]
  [-0.6976296  -1.42009277 -2.1721541 ]]

 [[-0.22838509 -0.37519744  1.66782364]
  [ 1.43768915 -1.09487356  1.04747471]
  [ 0.33689052  0.275661   -0.36065237]
  ...
  [ 1.37536707 -1.34714861  0.4179874 ]
  [ 1.25518548  0.08937847 -0.38407111]
  [ 0.74537879 -0.65397545  0.8516325 ]]

 ...

 [[-0.37674741 -1.16126946 -0.93798572]
  [-0.54469493 -0.60188905 -2.55701014]
  [ 1.11669524  0.07882463  0.12070514]
  ...
  [ 1.98939128  0.40588069 -1.09759433]
  [ 0.29260663 -0.81384517  0.90758287]
  [ 0.89255685  0.0051907   1.13682847]]

 [

In [28]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print(c.shape)

(2, 3)


In [29]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [31]:
X =[1,2,3]
print(X.shape)

AttributeError: 'list' object has no attribute 'shape'

In [32]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [53]:
# a.shape = (3,4)
# b.shape = (4,1)

a = np.random.randn(3, 4) # a.shape = (4, 3)
b = np.random.randn(4, 1) # b.shape = (3, 2)

for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]
print(c.shape)

c2=a+b.T
print(c2.shape)

(3, 4)
(3, 4)


In [50]:
c=a+b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

In [57]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(a)
print(b)
print(c)

[[-2.01781764 -1.42790189  0.99703444]
 [ 0.56450753 -0.13483571 -0.82163009]
 [ 1.16909131 -1.45292947  0.69495812]]
[[1.42372519]
 [0.31211923]
 [0.41743443]]
[[-2.87281781 -2.0329399   1.41950305]
 [ 0.17619365 -0.04208482 -0.25644655]
 [ 0.48801897 -0.60650279  0.29009945]]


In [ ]:
J = a*b + a*c - b+c


In [3]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
print(B.shape)

(4, 1)


In [1]:
for(i in range(1, len(layer_dims)/2)):
  parameter[‘W’ + str(i)] = np.random.randn(layers[i], layers[i-1])) * 0.01
  parameter[‘b’ + str(i)] = np.random.randn(layers[i], 1) * 0.01

SyntaxError: invalid syntax (<ipython-input-1-469993560ffb>, line 1)